### ISSUE TITLE
Create/update Design Token documentation (epic)

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#10170]
```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/10409
- [ ] https://github.com/Shopify/polaris/issues/10412
- [x] Update Type token docs
```

**Comment by Saharshjain78** [comment]
Hi @sarahill , I would like to contribute to this issue, can you provide some more information about this?

**Comment by sarahill** [comment]
Hey @Saharshjain78, thanks in your interest in helping with this! This work is part of token updates we're making for v12. The polaris team will be owning these updates but once we release the initial documentation we'll be open to thoughts and feedback from the community.

If you're interested in other opportunities to contribute, here's some [good first issues](https://github.com/Shopify/polaris/issues?q=is%3Aissue+label%3A%22Good+first+issue%22+is%3Aopen).

**Comment by Saharshjain78** [comment]
Hi Sara,

Thank you for reaching out, and I appreciate the update regarding the token
updates for v12 in Polaris. It's great to hear that the Polaris team is so
keen on community feedback.

I'll definitely keep an eye out for the documentation and  I'll be happy to
explore the good first issues you've mentioned for other opportunities to
contribute.

Thanks again for keeping me in the loop, and I look forward to being a part
of the Polaris community's progress.

Best regards,
Saharsh Jain
