### ISSUE TITLE
[Storybook] Remove the se23 and shadow bevel toggle

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10190]
Also clean up `polaris-react/playground/DetailsPage.scss`
```[tasklist]
### Tasks
- [x] Remove se23 toggle and any feature flag logic from `polaris-react/.storybook`
- [x] Remove se23 shadow bevel opt out toggle and any feature flag logic from `polaris-react/.storybook`
- [x] Remove any instances of `STORYBOOK_SE23='on'`
- [x] Remove feature flag story
```

**Comment by laurkim** [comment]
Partially addressed by [10242](https://github.com/Shopify/polaris/pull/10242).
Remaining storybook clean up can happen with AppProvider consolidation.
