### ISSUE TITLE
[CI] Remove pre se23 CI checks (CI and a11y/vrt) and remove experimental name from new checks

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#10191]
```[tasklist]
### Tasks
- [x] Delete `.github/workflows/ci.yml`
- [x] Delete `.github/workflows/ci-a11y-vrt.yml`
- [x] Rename `.github/workflows/ci-experimental.yml` to `.github/workflows/ci.yml`
- [x] Rename `.github/workflows/ci-a11y-vrt-experimental.yml` to `.github/workflows/ci-a11y-vrt.yml`
```
