### ISSUE TITLE
[Card Layout] Single section, single list

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#10316]
## Visual
![image](https://github.com/Shopify/polaris/assets/38329124/4f274c2d-75c0-4787-afdf-4b67062b38f1)
[Source](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=494%3A10897&mode=design&t=wLYenkRbuXnSxCxK-1)

## Builder needs
In order to design and implement this pattern consistently, builders need to:
1. Understand basic spacing between heading and list
2. Understand basic spacing between between list items
3. Know when and why to make exceptions that accommodate common scenarios

## Key information
1. **Default rule:** Use `space-2` (8px) between heading and list, and `space-1` (4px) between list items
2. **Rule:** `space-1` (4px) is always reserved for the closest relationship. When list items have children, that relationship is between those children. In those cases the list items use a `space-2` (8px) gap between peers.
3. **Rule:** List items can have inner white space caused by padding or content such actions. In those cases, reduce the gap towards `space-0` (0px) until the perceived gap is as close to the desired value.

```[tasklist]
### Tasks
- [x] Draft visual for critique
- [x] Outline what builders need to understand
- [x] Draft key information
- [x] Help builders distinguish line item types; default, with children, with white space
```
