### ISSUE TITLE
Manual color token updates (epic)

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#10351]
Update color token application for components as part of the token reconciliation work for v12. There are a couple cases where we will need to manually update polaris components to get the appropriate tokens.

### Updating components to use `on-bg-fill` colors

With the introduction of `bg-fill` and `on-bg-fill` colors the previous on-color tokens don't have a direct 1:1 mapping and need a manual update to get the expected visual style. We'll need to make this update in `web` too.

### Clean up color token application

The other case is cleaning up hacky token application from the uplift. In some cases, we had to use a mix of roles to get the colors we needed because the current system wasn't scaling to our needs. Now, we can update polaris components for consumers to use an example of token application in the udpated system.

```[tasklist]
### Manual color token migrations
- [ ] https://github.com/Shopify/polaris/issues/10371
- [ ] https://github.com/Shopify/polaris/issues/10350
- [ ] https://github.com/Shopify/polaris/issues/10352
- [ ] https://github.com/Shopify/polaris/issues/10353
- [ ] https://github.com/Shopify/polaris/issues/10387
- [ ] https://github.com/Shopify/polaris/issues/10375
- [x] https://github.com/Shopify/polaris/issues/10392
- [ ] https://github.com/Shopify/polaris/issues/10486
- [ ] https://github.com/Shopify/polaris/issues/10362
- [x] https://github.com/Shopify/polaris/issues/10391
- [x] https://github.com/Shopify/polaris/issues/10487
- [x] https://github.com/Shopify/polaris/issues/10354
- [ ] https://github.com/Shopify/polaris/issues/10763
- [ ] https://github.com/Shopify/polaris/issues/10373
- [ ] https://github.com/Shopify/polaris/issues/10721
- [ ] https://github.com/Shopify/polaris/issues/10386
- [x] https://github.com/Shopify/polaris/issues/10388
- [ ] https://github.com/Shopify/polaris/issues/10374
- [ ] https://github.com/Shopify/polaris/issues/10765
- [ ] https://github.com/Shopify/polaris/issues/10358
```
