### ISSUE TITLE
New page layout for section grid pages

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#10461]
Top-level section pages that render grid items should receive this new visual treatment. This includes:
* `/design`
* `/components`
*`/patterns`
* `/tools`

[Figma](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT/Uplift-polaris.shopify.com?type=design&node-id=43%3A26217&mode=design&t=kQj4os2WflWtJs5B-1)

### Technical details

Page rendered by the [`pages/[...slug].tsx`](https://github.com/Shopify/polaris/blob/next/polaris.shopify.com/pages/%5B...slug%5D.tsx#L86) template

Grid is the [`RichCardGrid`](https://github.com/Shopify/polaris/blob/next/polaris.shopify.com/src/components/RichCardGrid/RichCardGrid.tsx) component. `RichCardGrid` components added into the section markdown.

Markdown content found in [`/content/design/index.md`](https://github.com/Shopify/polaris/blob/next/polaris.shopify.com/content/design/index.md?plain=1)

### Tasks
- [ ] Three column grid
- [ ] Grid items are cards with an image OR an icon + background color combo
- [ ] No page title, breadcrumb, or lede

![Image](https://github.com/Shopify/polaris/assets/4642404/e605b06b-d7fc-4998-8dd7-d77ca07daf52)

**Comment by sophschneider** [comment]
FYI Page title "Design" is back in the figma mocks

<img width="769" alt="Screenshot 2023-09-18 at 3 50 54 PM" src="https://github.com/Shopify/polaris/assets/20652326/c319db5b-945e-47b7-9c50-35a75a3cc3f9">

**Comment by sophschneider** [comment]
Asked a question[ here on figma ](https://www.figma.com/file/vO0wToyBpYjeIwr8doAAWT?node-id=43:26217&mode=design#559259542) about max page widths.

> Right now the website has a universal max page width of 1192px.

> In this figma:
> * Content page with table of contents: 1236px
> * Home page: 1277px
> * Section root grid: 1040px

> Should we be updating the website max page widths to not be universal anymore? I only ask since max width is the only way to show this three column layout opposed to the 4 column that exists today

**Comment by sophschneider** [comment]
are there designs for this in light mode? what should the card content background be in light mode?

**Comment by gwyneplaine** [comment]
New Card component is in `next` now 
https://github.com/Shopify/polaris/issues/10150

**Comment by sophschneider** [comment]
I noticed that card component has a shadow bevel but the designs for the card grids don't. @tjonx should we be using a different component?

**Comment by sophschneider** [comment]
un assigning myself for now as I work on some other v12 work
