### ISSUE TITLE
[UI Kit] Migrate color styles to variables

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#10483]
```[tasklist]
### Tasks
- [x] Account connection
- [x] Avatar
- [x] Badge
- [x] Banner
- [x] Button - gradient, focus
- [x] Button group
- [x] Callout card
- [x] Card
- [x] Card alpha
- [x] Checkbox
- [x] Choice list - focus
- [x] Color picker
- [x] Contextual save bar
- [x] Data table - sort icon
- [x] Date picker
- [x] Description list
- [x] Divider
- [x] Drop zone
- [x] Empty state
- [x] Filters legacy
- [x] Fullscreen bar
- [x] Footer help
- [x] Grid
- [x] Inline error
- [x] Index filters
- [x] Index table
- [x] Keyboard key
- [x] Layout
- [x] Link
- [x] Media card
- [x] Modal
- [x] Navigation
- [x] Option list
- [x] Page
- [x] Page actions
- [x] Pagination
- [x] Popover
- [x] Progress bar
- [x] Radio button
- [x] Range slider
- [x] Resource list
- [x] Select
- [x] Setting toggle
- [x] Skeleton thumb, display text, body
- [x] Spinner
- [x] Tabs
- [x] Tabs legacy
- [x] Tag
- [x] Text field
- [x] Toast
- [x] Tooltip
- [x] Top bar - alert feed
- [x] Video thumbnail
```
