### ISSUE TITLE
Generic migrator issues

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#10909]
I ran test of a generic prop migration from color to tone on Icon:

`npx @shopify/polaris-migrator react-rename-component-prop "app" --componentName="Icon" --from="color" --to="tone"`

Noticing errors in irrelevant file types (.json, .scss):
```
zh-TW.json Transformation error (Missing semicolon. (2:14))
SyntaxError: Missing semicolon. (2:14)
```

```
ContentPill.scss Transformation error (Unexpected token (1:0))
SyntaxError: Unexpected token (1:0)
```

Noticing formatting changes in test files (unnecessary addition of parenthesis)
```tsx
jest.mock(
  '../ActivitiesCreate',
  () =>
    (function ActivitiesCreate() {
      return null;
    }),
);
```

Results: 
Lots of errors: `118180`. From checking wrong file types
Lots of unmodified: `49914` Files that don't have imports
Lots of time elapsed: `2623.537 seconds` i.e. `43 minutes` locally for one migration out of many.

```[tasklist]
### Tasks
- [ ] Make sure we're only checking files that have the component import or pass in a flag for file type i.e. .tsx
- [ ] Prevent formatting changes
- [ ] Investigate ways to boost performance
```

**Comment by aaronccasanova** [comment]
You likely need to update your glob pattern to be more specific e.g. from `app` to `app/**/*.{ts,tsx}`. That said, I wouldn't recommend using the `react-rename-component-prop` migration as it updates any matching component name regardless if it comes from Polaris or not. I'm working on a [new generic migration](https://github.com/Shopify/polaris/pull/10878) right now that only updates Polaris components and addresses a few more known edge cases.

The latest snapshot is pretty stable. Feel free to give it a go!

```sh
npx @shopify/polaris-migrator@0.0.0-snapshot-release-20231005161613 react-update-component-prop \
  --componentName Icon \
  --fromProp color \
  --toProp tone \
  'app/**/*.{ts,tsx}'
```
