### ISSUE TITLE
Complete layout for new Design guidance documentation

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#11019]
```[tasklist]
### Tasks
- [x] Update Icons layout
- [x] Update Motion layout
- [x] Update Typography layout
```
