### ISSUE TITLE
[polaris.shopify.com][Pattern]Update picker pattern

### ISSUE THREAD

**Issue by salmaamzil** [Shopify/polaris-react-archive#11050]
## Issue summary

Update the picker pattern (searchable listbox) to include multi-select.
Add different states: before / during / after selection

## Design tasks

**Customers-Segmentation-Automation team**

- [x] Finalize design pattern with stakeholders 
- [ ] Create a draft/skeleton for the picker pattern doc: consider generic categories instead of resource types (segments, locations...)
- [ ] Update content in each section to add multi select
- [ ]  Work with FED on implementation and code snippets that we can add

## Polaris feedback 

- [ ] Final design direction 
- [ ] Docs content (collab with @johanstromqvist ) 

```[tasklist]
### Tasks
```
