### ISSUE TITLE
[Tag] Updates

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#11096]
```[tasklist]
### Tasks
- [x] Update Remove icon disabled color
- [x] Remove border from clickable when disabled
- [x] Update icon color for removable button on hover and focus
- [x] Left padding should be tighter if an icon is present - updated in storybook example but there might be a better long-term solution)
- [ ] Focus state of remove button should be tighter
- [ ] Remove icon is getting scaled
```
