### ISSUE TITLE
`/icons` page search is broken

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#11121]
```[tasklist]
### Tasks
- [x] Icons are duplicated in the list because of Major/Minor metadata
- [x] Search is unpredictable and does not yield correct results
- [x] Search query on page load does not load correct icons list
```
