### ISSUE TITLE
Add `HoverCard` to `Destination` column in orders index

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#11746]
[Example of beta flag use](https://github.com/Shopify/web/pull/113173/files#diff-53143fb18f38776b4ce124496045008cb3d4680969647f0ba9add26e0f10855dR31) 

Migrate the existing `Peek` content from the `DestinationCell` into the new `HoverCard`. There should be no UI changes to the peek contents, check with @yoummyy for UX sign off

```[tasklist]
### Tasks
- [x] Merge https://github.com/Shopify/shopify/pull/491090
- [x] Merge https://github.com/Shopify/web/pull/121459
- [ ] Set up the `Destination` column in the orders index to use the `HoverCard` component behind the `polaris-orders_hovercard` beta flag
```
