### ISSUE TITLE
[Release 1] Implement CSB leave confirmation shake on key workflows

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#12000]
Copied from https://github.com/Shopify/archive-polaris-backlog-2024/issues/1472

```[tasklist]
### Tasks
- [x] Add a mechanism to shake the top bar that the consumers can access
- [x] Replace leave confirmation modal with shake on key workflows including but not limited to product details, create order, create/edit customer (anything accessible by main nav)
- [x] Debounce the shake so when spamming the action the animation is unaffected
- [x] Announce leave confirmation on screen readers and return focus to CSB discard button when attempting to leave without discarding
- [x] (Design needed) Find an accessible solution to notify leave confirmation when prefers-reduced-motion and or is color blind
- [ ] https://github.com/Shopify/polaris-internal/issues/131
```
