### ISSUE TITLE
[Release 1] Release Feedback

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#12269]
New features or UX tweaks from vault review for release. These are issues that are net new features/UX, so with the beta flag off they also don't exist

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/12265
- [ ] https://github.com/Shopify/polaris/issues/12267
- [ ] https://github.com/Shopify/polaris/issues/12266
- [ ] https://github.com/Shopify/polaris-internal/issues/389
- [ ] https://github.com/Shopify/polaris-internal/issues/391
- [ ] https://github.com/Shopify/polaris-internal/issues/399
- [ ] https://github.com/Shopify/polaris-internal/issues/390
- [ ] https://github.com/Shopify/polaris-internal/issues/285
- [ ] https://github.com/Shopify/polaris-internal/issues/346
- [ ] https://github.com/Shopify/polaris-internal/issues/345
- [ ] https://github.com/Shopify/polaris-internal/issues/455
- [ ] https://github.com/Shopify/polaris-internal/issues/442
```

**Comment by sophschneider** [comment]
Moving unclosed issues over to clean up epic https://github.com/Shopify/polaris-internal/issues/87
