### ISSUE TITLE
Interactive elements

### ISSUE THREAD

**Issue by yesenia-perezcruz** [Shopify/polaris-react-archive#4521]
So much of Admin revolves around interactive tasks — Navigating, Creating, Reading, Updating and Deleting things. Right now, every team is implementing their own version of this without guidance. Sometimes it results in an index view, sometimes an autocomplete. Merchants never know what to expect.

The admin DL should provide consistent patterns for this. As an example, anywhere where you can Delete a list item, there should be a consistent pattern in place.

- https://github.com/Shopify/polaris/issues/5382
- [ ] Delete patterns for pages, cards, modals, lists...
- [ ] Create patterns for pages, cards, modals, lists...
- [ ] Update patterns for pages, cards, modals, lists...
- [ ] Navigation patterns for pages, cards, modals, lists...
- [ ] Interactive patterns for links, buttons, form elements...
