### ISSUE TITLE
polaris-react 90% token coverage for color, motion, type, spacing

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4528]
## Project links

- [Project brief](https://docs.google.com/document/d/1C5JvYXYcm2wwhAWvofZaYSGmz9PZvOcVu9DOoXzwBvk/edit)
- [Vault project](https://vault.shopify.io/projects/22300)

## Summary

As of today we cannot roll out a new style to the admin or polaris-react components without updating multiple repos, thousands of lines of code, Sass functions and CSS custom properties. Teams building new components have multiple different ways to use tokens and the documentation is in multiple places. The goal of this project is to guarantee every component in polaris-react used in shopify/web is built with simple tokens from one place.

This work will create a platform for teams to build custom components in shopify/web and enable us to ship large design infrastructure changes through our components.

**Intended outcomes**
- 100% of polaris-react components are built with tokens.
- Consolidate tokens into one place and use CSS custom properties.
- Teams have one implementation of tokens to use.
- Remove all deprecated css custom properties and token related Sass functions.
- Remove runtime theming.
- polaris.shopify.com includes simple documentation for tokens.
- 2022 - New major version of polaris-react shipped to @shopify/web.

**Key assumptions**
- shopify/web will use the updated css custom properties.
- Centralising the tokens will make it easier to identify foundational components.
- Existing tokens are limiting and confusing to use.
- It’s easier to hard code design values than use tokens today.

**Guiding principles**
- Simplification over complexity.
- Prioritise a tolerable solution not a new token system or library.
- Get shit done.

## Breakdown

**Infrastructure**
- [x] #4586
- [x] #4587
- [x] #4588
- [x] #4589
- [x] #4590
- [x] #4591
- [x] #4732

**Color**

- [x] #4592
- [x] #4593

**Motion**
- [x] #4595
- [x] #4596
- [x] #4597

**Typography**
- [x] #4598
- [x] #4599
- [x] #4600
- [x] #4601
- [x] #4602

**Spacing**

- [x] #4603
- [x] #4604
- [x] #4605
- [x] #4606

**z-index**

- [x] #4607
- [x] #4608

**Layout**

- [x] #4609
- [x] #4610

**Border radius**

- [x] #4611
- [x] #4612
- [x] #4613

**Border width**

- [x]  #4891

**Shadow**

- [x] #4614
- [x] #4615
- [x] #4616

**Documentation**

- [x] https://github.com/Shopify/polaris-styleguide/issues/4905
- [x] https://github.com/Shopify/polaris-styleguide/issues/4904
- [x] https://github.com/Shopify/polaris-react/issues/4706

**Replace em() function**

- [x] #4777

## v9.0.0

- [x]  https://github.com/Shopify/polaris-react/issues/4910
- [x]  https://github.com/Shopify/polaris-react/issues/4706
- [x]  #4748

## After v9.0.0 ships

- [x] #5314
- [x] Benchmark for ThemeProvider vs CustomProperties
- [x] #5359
- [x] #5339
- [x] #5354
- [x] #5363

**Comment by alex-page** [comment]
Closing this issue. Remaining work tracked in this GitHub project board view.
https://github.com/orgs/Shopify/projects/2250/views/44?type=beta
