### ISSUE TITLE
Simplify release and changelog process

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#4529]
The [Polaris release process](https://docs.google.com/document/d/1sjbYdZb1VqhZori-WlmqrpiZW-Xx7xLBbFekbvFIU4g/edit) is outdated, hard to follow and often causes issues with tagging releases and shipping to NPM. It has slowed down multiple product teams (Deliver) from efficiently shipping new features to shopify/web.

Getting the release process down to 2 steps will increase velocity, reduce forked components, increase contributions and allow our team to work with product teams more efficiently.

- [x] Remove release branch
- [x] Remove [changelog.md](https://github.com/Shopify/polaris-react/blob/main/CHANGELOG.md) and [unreleased.md](https://github.com/Shopify/polaris-react/blob/main/UNRELEASED.md) use [auto-generate release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
- [x] Tag commits through the release UI
- [x] When release published from GitHub UI automation is ran to:
  1. bump package.json
  2. publish NPM package (either with button press on shipit or automation)
- [x] Document release process in README.md file (alpha, patch, minor, major)
- [x] Communicate release process to teams
