### ISSUE TITLE
Improve page loading experience

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#4765]
## Problem summary
Page loading experiences in Admin are ineffective, especially the design and use of skeleton content. Jumpy, shifty and uninformative layouts cause cognitive resource leaks that slow merchants down.

- [Vault project](https://vault.shopify.io/projects/22578)
- [Figma planning and jamming](https://www.figma.com/file/Fumq1G6wRWQcMrZexnt3wq/Performance-jam?node-id=10%3A244)
- [Figma design project](https://www.figma.com/file/8TrajsVOG8UsFopC2iAZuh/Page-load-performance?node-id=0%3A1)

## Audit

The biggest problem today is that layouts are 
- Jumpy: multiple visual updates over a short period of time
- Shifty: the first visual update rarely resembles the last update

### Screenshots

Examples of the first paint when loading Products index and Analytics dashboard.

**Products index**
![product index](https://user-images.githubusercontent.com/38329124/144111038-3407e95e-c374-473c-bc5f-3ef4439c047b.png)
**Analytics dashboard**
![analytics dashboard](https://user-images.githubusercontent.com/38329124/144111040-a1ddee82-8d6f-4984-a6b5-be5e42964381.png)

### Performance audit

Lighthouse performance audit shows that both perceived and absolute performance is in critical need of attention. It's also clear that there are limitations to how well we can programmatically assess the user experience, e.g. when looking at the `cumulative layout shift` score of the Analytics Dashboard.

| Products index | Analytics dashboard |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/38329124/144113449-8bd6a599-1f2b-40cf-9477-4cd1ba9e4f4c.png) | ![image](https://user-images.githubusercontent.com/38329124/144113523-5cd3fd49-d20b-4d76-a8f8-2998ed7799a4.png) |

## Early ideation

- Deprecate the [Skeleton page component](https://polaris.shopify.com/components/feedback-indicators/skeleton-page#navigation) and the [Loading component](https://polaris.shopify.com/components/feedback-indicators/loading#navigation)
- Replace skeleton loading experiences with "dataless states"
- "Dataless states" have accurate layout, static content, and controls
- Benefits: very stable, trustworthy, and high signal which enable users to stay focused on the task and act on their intent sooner
- Tradeoffs: more labour intensive, and may delay first paint

**Products index**
![dataless products](https://user-images.githubusercontent.com/38329124/144111088-9841bbd4-841f-4690-be22-8e94107a5df6.png)
**Analytics dashboard**
![dataless analytics](https://user-images.githubusercontent.com/38329124/144111085-0c9c02ef-e745-40ca-b3ef-4fc319b8f1b4.png)

## Prototypes
- [Product index](https://principle.app/share?id=eBite46rPiBpD2gb55gn) (click products in main nav)
- [Analytics dashboard](https://principle.app/share?id=Wx6MKr8Ftx9vfJxyQTSN) (click analytics in main nav)

### Progressive Web Apps (PWA)
Web tech such as service workers and manifests can be leveraged to cache dataless states, which allows us to both deliver trustworthy loading layouts and fully interactive pages sooner. PWA has been tested successfully in the Admin.

| Spotify PWA |  |
| -- | -- |
| >100ms | ![image](https://user-images.githubusercontent.com/38329124/144118051-b93dec52-dfde-4840-bb97-6048495d33b5.png) |
| 100-200ms | ![image](https://user-images.githubusercontent.com/38329124/144118433-c00a499a-2e04-48b4-a454-a760e3789dc3.png) |
| 200-300ms | ![image](https://user-images.githubusercontent.com/38329124/144118558-a52d8b23-7dc7-4bc9-9c0b-6f7e4611f2bc.png) |

### Preloading
Preloading can be leveraged to finish loading sooner. Ideas:
- On hover: Start loading content on button hover instead of on button press. Expected win: `500ms`
- Anticipated hover: Measure the trajectory and velocity delta of the cursor to anticipate users' intent to navigate. Expected win: up to `1000ms` (🧑‍🔬  experimental)
- On parent or sibling page load: Start loading the next available page when the current page is done loading, e.g. preload product index and analytics dashboard when home page is done loading.

### Async and progressive loading
Asynchronous and progressive loading can be leveraged to make sure that the most important data is loaded first and any secondary data is deferred. Many pages are already leveraging async loading, but without any data prioritizations.

In the example below, we can see how the product index is loading five payloads separately, but secondary data that is hiding behind another interaction (`collections for filters`, `app links` and `filter values`) starts loading sooner than the most important data (`product index` and `saved searches`)

![image](https://user-images.githubusercontent.com/38329124/144117164-b94dbc07-397b-4167-89ad-b1592a4bc361.png)

**Comment by johanstromqvist** [comment]
Brainstorming some next steps here @dfmcphee 

## Project
- [ ] Iterate on the goals, scope and deliverables, and share with stakeholders
- [ ] Review the time plan and make a more informed estimate
- [ ] Identify the ICs and stakeholders
- [ ] Identify the key perspectives from around Shopify

## Technological opportunity
- [ ] How feasible is a PWA approach?
  - [ ] Find the past Admin PWA explorations (Daria, Malory, ...?)
  - [ ] Gather learnings
- [ ] What could various technical opportunities help us achieve?
  - [ ] Async loading?
  - [ ] Data prioritization?
  - [ ] Progressive loading?
  - [ ] Progressive Web Apps?
  - [ ] Server Side Rendering?
- [ ] What opportunities haven't we considered yet?
- [ ] Should we utilize all or focus on some?

## Insight
- [ ] What metrics can we get from various sources?
  - [ ] Fast.shopify.io?
  - [ ] Lighthouse?
  - [ ] Admin DevUI?
  - [ ] Manual UX assessment?
- [ ] How do these metrics complement or contradict each other?
- [ ] What type of decisions can they help us make?
- [ ] Connect with Leo and Sophie on FED foundations regarding DevUI additions
  - [ ] Can we create an experience quality score?
  - [ ] How else can DevUI consider what queries are being fired and in what order?

## Solutions
- [ ] What might some reusable UX/Eng patterns look like?
- [ ] What might a UX score look like?
- [ ] What might empowering guidelines look like?

**Comment by johanstromqvist** [comment]
@michenly was kind to provide engineering perspective and feedback on the initial proposal.

> Here are my thoughts on the project. Let me know if you would like to chat about it over huddle or something tomorrow. 
1. **Jumpy**
IMO this is mostly due to the order the data was loaded was never carefully guarded per page.
This can likely be improve with React 18 (currently a RC)’s Suspend with fallback feature (https://reactjs.org/docs/concurrent-mode-suspense.html) to ensure all pages has a clear order of how and when the data should be loaded.
2. **Shifty**
Predicting the right size of text or graphic that will be loaded is highly important.
Things that play a part into this prediction will be responsiveness and i18n that can affect the length of text.
3. **Preloading**
This does actually currently exist (https://github.com/Shopify/quilt/tree/main/packages/react-async#preload-prefetch-and-keep-fresh). Usually use for hovering on sidebar and preloading the data & async components needed.
Its not the easiest to set up and can be improve from dev ex point of view. At the same time more example & guidance on when UX would like to involve this can help drive more usage.
4. **Async and progressive loading**
Watch out for when “dataless states” is not truly “dataless”
A blind spot I want to point out using the product index example you shown & the suggested loading experience. Is that with the new product index experience, the filters are shown before the product details.
This means end user can interact with the filters before the details is loaded - which I assume is the intention. But this will go directly against the proposal of loading `product index` & `saved searches` before `collections for filters`. In this new loading experince the order of data loaded is ideal.
While I overall does understand your intention for using this example, it need to be revised to go with the suggsted experience going forward.
5. **PWA**
I found an old issue where we remove the PWA app shell experiment to give more context. https://github.com/Shopify/web/pull/11984
As TL;DR, the things that made the experiment really difficult is around cache invalidation. When and how often to do this. PWA relied heavily on cache and knowing what are parts of your application that does not change often that can be cache.
Most of admin (even just the top bar and side bar) and highly dynamic (think language change, installing / uninstalling sales channel) which makes the benefit of PWA go down significantly.
Specially around using PWA to cache dataless states. We will need to measure the time it take to render a dataless component in React vs loading this from cache and how often we invalidate the cache.
6. **Prototype for 1st iteration**
To deal with jumpy-ness and shiftiness, I think it can be started without any additional technology (PWA or React Suspense)
Both of those technology give us better dev ex and therefore better scalability down the road.
But to make a dataless state with accurate predictable text size, or to load the data in the correct order, those are both things that can be try without the consideration of good dev ex at first.
