### ISSUE TITLE
Figma UI Kit component audit

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#4963]
[Project Brief](https://docs.google.com/document/d/1NJXSSUg3tLlaCRxvJF17IopOA7lbXUhYsZRvhoxXsm0/edit?usp=sharing) 
[Vault project](https://vault.shopify.io/projects/23707)

## TLDR
The Figma UI Kit needs a tune up to get it up to date with the current state of the system. There are bugs to fix, design changes not applied and missing components. The goal of this project is to bring the UI Kit to a healthy and stable place.

## Tasks

- [x] Add change log to UI Kit for documentation of changes
- [x] Remove unwanted dependencies from UI Kit so only correct Polaris styles are being used
- [x] Audit UI Kit components against Polaris repo and document everything that is missing or incorrect
- [x] Fix Actions components styles and variants [Github issue](https://github.com/Shopify/polaris-react/issues/5147)
- [x] Fix Structure components styles and variants [Github issue](https://github.com/Shopify/polaris-react/issues/5204)
- [x] Fix Forms components styles and variants [Github issue](https://github.com/Shopify/polaris-react/issues/5285)
- [x] Fix Images and Icons components styles and variants [Github issue](https://github.com/Shopify/polaris-react/issues/5278)
- [x] #5372
- [x] #5373
- [x] #5374
- [x] #5375

**Comment by heyjoethomas** [comment]
Project is complete with latest release 🎉
