### ISSUE TITLE
Designers, developers and tool builders have access to the latest tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5073]
## Project links
- [Project brief](https://docs.google.com/document/d/1OHCMlVWkodxeNGtDmwKfF-xJH9FmgsZ-0VLYO9i-IL8/edit)
- [Vault project](https://vault.shopify.io/projects/23655)

## Summary

Increase coverage by making it easy to reference and consume our tokens.

In order to increase coverage in the admin (https://vault.shopify.io/projects/22300), polaris-react v9 deprecates Sass methods in favour of CSS custom variables. Our website should support this roll-out by making listing all the tokens and educating crafters on how to use them. Additionally, developers should be able to access the tokens thorough an NPM package and our API.

## Outcomes

- Designers and developers understand why they should use tokens
- Designers and developers can easily reference our tokens
- Developers access our tokens in efficient ways: through an NPM package and through our API.

## Website

- [x] #5084
- [x] #5076
- [x] #5077
- [x] #5085
- [x] #5086
- [x] #5087
- [x] #5088
- [x] #5089
- [x] #5090
- [x] #5091
- [x] #5092

## NPM package
- [x] #5095
- [ ] Remove javascript token files from `polaris-react` build
- [ ] Deploy JSON files
- [ ] Publish into polaris-tokens package

## API
- [x] #5083
- [x] #5105
- [ ] _API is versioned based on tokens?_
- [x] #5189

## Figma plugin

**Migrated to #5231** 

- [x] #5096
- [x] #5097
- [x] #5101
- [x] #5098 

## VSCode plugin

- [x] #5104
- [x] #5106
- [x] #5107

**Comment by jjgali** [comment]
Not sure who is working on Figma plugin, but happy to help with documentation write/review if needed.

**Comment by rahilllshah** [comment]
Had a look and made some edits from my end for the Figma plugin! @martenbjork @emma once it's good from your ends too we can make them issues!

**Comment by alex-page** [comment]
Closing this issue as the vault project is complete.
