### ISSUE TITLE
Deploy polaris-tokens NPM package from monorepo

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5442]
- [ ] Fix up readme
- [ ] Remove polaris-tokens github pages site
- [ ] Migration guidelines for new major version
