### ISSUE TITLE
Establish infrastructure baseline

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-react-archive#5459]
**Vault project:** https://vault.shopify.io/projects/25007

This work will set us up to make scalable infrastructure improvements as `Shopify/polaris` continues to grow:

Problems we are solving:

- [x] Identify clear next-steps for Polaris-owned repositories not within the Shopify/polaris monorepo.
- [x] Updating documentation so that contributing to the new monorepo is clear and accurate.
- [x] Establish structure of monorepo by cleaning up legacy and redundant files.
- [x] Address critical deployment or runtime-related issued generated by other Shopify services.
- [x] Audit npm dependencies and update any high-severity packages and improve Dependabot automation.

This will result in the following outcomes:

- [x] Resolve all issues created by Shopify services
- [x] Set up the initial root-level monorepo configuration
- [x] Documentation reflects the new monorepo structure
- [x] Create initial setup for cross-package development
- [ ] ~~Implement a new process for Dependabot for Polaris-owned repositories~~ (will continue to triage and address Dependabot issues with the same process)
