### ISSUE TITLE
Release and changelog improvements

### ISSUE THREAD

**Issue by sam-b-rose** [Shopify/polaris-react-archive#5665]
## Overview

**Vault project: TBD**

Our current release process is manual and prone to human error. Appending to the changelog is only done for one of the packages, `polaris-react`, and doesn’t scale well to the other packages.

We currently don’t have the proper tooling in place to tag, version, and release packages simultaneously. There are individual `shipit.*.yml` files defining how to release each for each package. This can be consolidated into a single file improving release consistency, reducing redundancy, and enabling simultaneous release.

Before adding more packages to the monorepo, it would be desirable to consolidate the release process to a standardized flow that can work for all packages, handle the versioning of each package, and append changelogs entries automatically–no more copy & paste!

### Tasks

- [x] Setup [Changesets](https://github.com/changesets/changesets) – 🦋 a monorepo tool for managing versioning and changelogs
- [x] Update CONTRIBUTING.md documentation to fit Changesets process
- [x] Update [Versioning and changelog](https://github.com/Shopify/polaris/blob/main/documentation/Versioning%20and%20changelog.md) documentation to fit Changesets process
- [x] Use `*` for monorepo workspace dependencies to use local package versions
- [x] Replace “🤖Skip changelog” label and check with Changesets GitHub Action to ensure changelog entry is added for new PRs

## Outcomes

- Reduce manual steps of the current release process. 
- Have a standardized change management log for ALL packages and a single release process. This will also improve developing across packages locally by using the local version of a workspace package.

**Comment by sam-b-rose** [comment]
Fixed by #5800
