### ISSUE TITLE
Publish Loading guidelines

### ISSUE THREAD

**Issue by johanstromqvist** [Shopify/polaris-react-archive#5872]
### Goal
Create an MVP that can provide immediate value internally.

- [x] Finish developing the raw content
- [x] Review content with content designer
- [x] Share guidelines ~internally~ publicly

### Next steps
The v1 is done. Future iterations include:
- Discussing with early users and improving contents 
- Create visual examples
- Align the article structure with other Polaris guidelines

**Comment by johanstromqvist** [comment]
# Principle
<details>
  <summary>Best practice</summary>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
</details>

**Comment by johanstromqvist** [comment]
Status: Ready for content review

# Loading guidelines [WIP]

Navigating the Admin should feel fast and easy, but loading can get in the way of that. Slow and jittery pages break the merchant's flow and can cause them to derail. It's our job to make sure that doesn't happen. The faster, more meaningful and more focused loading experiences we design, the more continuous the merchant experience becomes, and the more likely it is that merchants stay productive.

## Principles:
1. **Minimum delay** – load as little as possible, as soon as possible
2. **Time well spent** – merchants can engage in meaningful activities
3. **Focus on the task** – merchants' attention is focused on what's important

# Minimum delay

![Timeline]

Pages should load as fast as possible and the most effective way to do that is to load as little data as possible, to prioritize the data that will unlock the most useful content, and to start loading it as soon as possible. When designing experiences it's important to develop an opinion on what content that merchants will need the most, when they will need it, and use that when designing the loading experience.

<details><summary>Cache commonly needed data</summary>
Caching data eliminates the loading time the next time it's needed. Consider caching data that is reused times throughout an experience, such as the name and image of an item, and use that to show essential content while other content loads.</details>

<details><summary>Prefetch data when it's likely to be needed</summary>
Prefetching data can save lots of valuable loading time. Start prefetching when merchants show intent to need the data, such as when hovering navigation or an interactive item.</details>

<details><summary>Prioritize content visible in the viewport</summary>
The content that is visible in the viewport is the content that merchants will likely need first. Make sure that such content isn't delayed by content that merchants won't need until after an interaction, such as scrolling or clicking a popover.</details>

<details><summary>Limit the amount of content on the page</summary>
Pages with a lot of content take longer to load. Sometimes that's meaningful, but sometimes it's not. By limiting the page content to what merchants will need, we can both speed up the loading and declutter the page. Use [progressive disclosure] to give merchants more content when they need it, and remember to prefetch it so it's readily available.</details>

# Time well spent

![loading-example-drake]

Merchants want to use their time to get work done, so we want to make sure that they can do that even during loading. Showing the right context, real page structure, and meaningful content will keep them engaged in what they are about to do and prepare them to take action once the content they need is available.

<details><summary>Switch to the next view quickly</summary>

![placeholder]

People expect to get the result of their interaction right away. When merchants are navigating to a new page or invoking a view, it’s typically best to move forward to that context immediately, rather than to load first and switch later. Sometimes that means that we have to revert to the previous view in case of errors, but that's often a reasonable tradeoff when success is the most common case.</details>

<details><summary>Make sure the loading layout is accurate</summary>

![loading-example-layout](https://user-images.githubusercontent.com/38329124/169505587-7f34c7e0-bdb7-41ac-b1d4-07f9c81dcb2f.png)

The page layout during loading should give merchants a head start to scan and understand the structure of the page. Make an effort to minimize the difference between the layout during and after. Highly matching layout sets clear expectations and make merchants proactive, but poorly matching layout misleads merchants and wastes their time.</details>

<details><summary>Show as much real content as possible</summary>

![loading-example-static](https://user-images.githubusercontent.com/38329124/169501005-14c03508-03e1-4915-982a-d5cf84447294.png)

Showing static content, such as section labels, icons, text and imagery, gives merchants a head start in understanding the page. A small thing like a labeled card can enable them to find what they need almost immediately. A lot of interactive content can be shown too. For example, when primary actions, such as "Add product", are the same to all merchants, then those could be included in the loading state. Ideally they are rendered active so that merchants can take action before the page is done loading. If the action can't be interacted with during loading, then render it disabled.</details>

<details><summary>Give hints with recognizable placeholders</summary>

![placeholder]

Placeholders let merchants anticipate where content will show up and what type of content it will be. Use placeholders for anything that is visually distinct, such as lists, images, controls, text, and data visualizations. This is the most important job skeleton content can do. Avoid detail in the placeholder if it’s not certain it represents something that will appear. We don't want to draw attention to it and set false expectations.

Learn more about [skeleton content]().
</details>

# Focus on the task

![task-focus-placeholder]

A clear loading experience is effortless and allows merchants to take action sooner. Anything unexpected, such as visual noise, doubt, or spinners, will attract their attention, and in worst case waste it. The task, the content, and the progress must always be at the centre of attention.

<details><summary>Give satisfying feedback on the initializing interaction</summary>

![placeholder]

Loading is typically a consequence of merchants navigating to a new page or view. If it's unclear that their initializing interaction worked, then their experience will start with doubt and confusion. When it's clear, then the interaction is a thing of the past and they can make better use of their time. Make sure that the feedback is noticeable within 100 ms and that it's clear what happened.

Learn more about [responsiveness]().</details>

<details><summary>Default to showing real progress</summary>

![placeholder]

The best way to inform people that the system is working is to show real progress. Real progress puts people’s attention on the content while providing something useful to work with. Progress within 1 second is perceived as natural and continuous, which keeps people engaged in the task. When actual progress can be shown within 1 second intervals, merchants typically don't need any other loading indicators.</details>

<details><summary>Use spinners when real progress isn't enough</summary>

![placeholder]

Spinners are only needed when it’s not clear that the system is working. Excessive use of loading indicators isn’t informative. Rather, it can be overwhelming and make the system appear slow. Use them only when it's certain that it will improve the user experience, and place them in close proximity to what they represents, such as a spinner at the top of a list with loading items.

Learn more about (Spinner usage]().

</details>

<details><summary>Avoid empty views with spinners</summary>

![placeholder]

It's important to make an effort to provide useful content during loading. Simply by being in the right visual context, seeing that progress is being made, or getting a glimpse of what's ahead goes a long way. Empty views with spinners provide almost nothing of value and cause people to become passive and disengage.</details>

<details><summary>Be honest with lengthy loading times</summary>

![placeholder]

People are likely to be frustrated and abandon their tasks if loading times exceed 10 seconds. In such cases it's better to set very clear expectations and empower merchants to make an informed decision to wait. Try to put their attention on the value ahead and that way increase the likelihood that they stay engaged in their task.</details>

<details><summary>Make sure the layout is stable throughout the experience</summary>

![placeholder]

It's very important that the layout doesn't unexpectedly change during the loading process. Merchants will engage with visible content and any unexpected change can throw them off. In most cases this will affect their focus, but in the worst case it can cause them to click something they didn't intend to click. Only show layout and content that will be there both during and after the loading experience.

Learn more about [visual stability](https://web.dev/cls)</details>

<details><summary>Minimize visual noise</summary>

![signal-noise-diagram]

Visual noise attracts a lot of attention, but provides no value. Merchants can easily get distracted and their attention span can get significantly shortened. Analyze the loading experience and pay attention to anything that changes throughout it.

- Remove any avoidable visual noise, for example by fixing poorly matching placeholders or by planning better for unexpectedly appearing content.
- Subdue any visual noise that is unavoidable, such as fading in content that render late or using transitions to make state changes less sudden. When the size of an element is variable and unknown, such as a product index with a variable number of items, then it's typically better to add too many placeholders than too few. It's less jarring when elements suddenly shrink compared to when they suddenly expand.
- Emphasize the visual change that matters, such as animating the items in a list or the most important information on the screen. Emphasizing important content will guide merchants' attention to what they want while also increasing the tolerance for other visual change on the page.</details>

---

Related components
- Spinner
- Loading bar
- Skeleton content

---

Related patterns
- Feedback
- Layout
- Timing
- Navigation
- Progressive disclosure

---

# Notes

### Phases
1. **MVP** – Users understand it is, why it's important, and what's the most important to achieve
2. **Actionable** – principles are made actionable by best practices
3. **Easy** – Best practices are made easy with infrastructure and reusable components


[placeholder]: https://user-images.githubusercontent.com/38329124/169508314-8e0a7051-5c6f-491b-9f8e-b0a571ec0499.png "Logo Title Text 2"

[progressive disclosure]: https://www.example.com

[signal-noise-diagram]: https://user-images.githubusercontent.com/38329124/169855527-cdd9e922-29cb-4c05-b010-6cee9fbad9af.png

[Timeline]: https://user-images.githubusercontent.com/38329124/169861021-f22afd6e-ce98-4372-8677-85f91cf60dd9.png

[state of flow]: https://www.verywellmind.com/what-is-flow-2794768#:~:text=Flow%20is%20a%20state%20of%20mind

[loading-example-drake]: https://user-images.githubusercontent.com/38329124/169506140-027a4f7b-ef48-4db1-9076-e438432acaae.png

[task-focus-placeholder]: https://user-images.githubusercontent.com/38329124/169892589-b9a16c97-214d-4002-968a-6076920420d6.png

**Comment by johanstromqvist** [comment]
Guidelines published here and here
- https://polaris.shopify.com/patterns/loading
- https://secretpolaris.shopify.com/guidelines/patterns/loading
