### ISSUE TITLE
[Typography foundations] Usability test with developers

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#5915]
## Goal

The goal of this research is to get developer feedback on two different approaches to typography components.

We want to understand which approach is easier to understand and start using with little onboarding while still providing an escape hatch to deviate from the baseline type styles when needed.

## Resources

- [Research plan](https://docs.google.com/document/d/1bMaykWH1bPPLTbHof1kA7mQP5lJw-p2lyuBnebpqaUI/edit#heading=h.5n4k3z2t01ea)
- [Discussion guide](https://docs.google.com/document/d/1JCVaGsJHyglkokE2ydm_P6QxwFtMwjm7CcoT9732y1s/edit#heading=h.1gzok5h1zhur)

## Todo

- [x] Recruit participants
- [x] Schedule sessions
- [x] Create discussion guide
- [x] Pick page/section to recreate for testing
- [x] Set up reference Figma file
- [x] Create code sandbox for testing

**Comment by laurkim** [comment]
Feedback from user testing sessions synthesized [here](https://www.figma.com/file/EBvzbsFtBIMZ4QlZ724z9a/Type-foundations-planning?node-id=7%3A216).

**Comment by alex-page** [comment]
WUhuuu awesome work everyone!
