### ISSUE TITLE
[Typography foundations] Release Alpha typography

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6793]
The work is pretty much done but we're waiting on v10 to merge and publish some things. This issue is tracking some outstanding things we'll need to do along side the v10 release.

## Tasks

- [x] Publish [Typography updates guide](https://docs.google.com/document/d/1Sg-Kdr560zYf97m5J948FYsmYCqQBw2jhW-F-MBMq9I/edit#) in style guide or GitHub discussion
- [x] Merge `text-styles` [branch](https://www.figma.com/file/tbm3yEIZsOuHS7xJu9zy6Q/text-styles?node-id=5523%3A51) in Figma
- [x] Share announcement in Slack
- [ ] Share announcement in Polaris Newsletter

**Comment by sarahill** [comment]
Putting the Slack post here so it's ready and formatted.

[All the gifs](https://drive.google.com/drive/folders/12U7fAgxv_EXZ6TnNlDFPundjN-2VonGB?usp=sharing)

## Slack post:

:tada: Hey folks! This week, with the release of v10, we made the new Polaris typography updates available in alpha. That means we’re making the new [`Text` component](https://polaris.shopify.com/components/text) and [Figma text styles](https://www.figma.com/file/JHp1kp7ghGmTHs147CHjDf/Polaris-Styles?node-id=5455%3A50) available to use but there could still be significant developments made. Our goal is to share the work so that you can: understand what’s changing, start using the type updates, and provide feedback to help us improve the system.

:construction: Please note: The updates are available to use but be aware there could be significant changes made. Please work with your team to determine what's best for your situation.

:eyes: Read the details of what's changing and how to start using the typography updates

:thread: Checkout the thread for highlights

![Image](https://user-images.githubusercontent.com/8629173/181581522-376bf41d-2b46-4f2c-8b5f-61a2c85482fa.png)

### Thread 1:
:figmaparty: The Figma text styles are available under Alpha in the styles text styles menu.

_add gif - 01-alpha-styles-menu_

### Thread 2:
:figmaparty: You can apply the new Alpha styles to an existing design. If you're not sure which one to use, just hover to see a description for each style.

_add gif - 02-text-style-menu-descriptions_

### Thread 3:
:figmaparty: See how the new styles map to the old ones on the  new :compass: [Guides page](https://www.figma.com/file/JHp1kp7ghGmTHs147CHjDf/Polaris-Styles?node-id=5523%3A51) in Polaris styles.

_add gif - 03-typography-figma-guides_

### Thread 4:
:figmaparty: Checkout the Alpha text style details in Polaris styles.

_add gif - 04-alpha-type-style-table_

### Thread 5:
:vscode: Alpha Text component example implementation with autocomplete for prop options

_add gif - 05-vscode-text-component_

### Thread 6:
:polaris6: Check out the new docs for the Alpha Text component on [polaris.shopify.com](http://polaris.shopify.com/) to see examples and mapping from previous Polaris typography components

_add gif - 06-alpha-text-component-docs_

### Thread 7:
:polaris6:  Checkout [updated guidance](https://polaris.shopify.com/foundations/design/typography) with some useful tips for designing with type. 

_add gif - 07-designing-with-type_

---

## Example

![Image](https://user-images.githubusercontent.com/8629173/181582323-4bb6b6ef-859c-4037-85e1-15f6c816322c.png)

**Comment by laurkim** [comment]
adding in code examples

### Thread 5:
:vscode: Alpha Text component example implementation with autocomplete for prop options
![alpha-text-component-example](https://user-images.githubusercontent.com/26749317/182885811-a577704e-f3bf-4eaf-895a-2254da78bcc4.gif)

### Thread 6:
:polaris6: Check out the new docs for the Alpha Text component on [polaris.shopify.com](http://polaris.shopify.com/) to see examples and mapping from previous Polaris typography components
[gif](https://screenshot.click/alpha-text-component-docs.gif)

^ last gif was too big to attach

**Comment by laurkim** [comment]
Messaging has been shared in relevant slack channels post v10 release.
