### ISSUE TITLE
[Typography foundations] Update UI Kit components with new text styles

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#6794]
The UI Kit components need to be updated to use the new text styles 

### Todo:

- [x] Update components with new text styles
- [x] Move new text styles out of Alpha
- [x] Move old text styles to deprecated folder

**Components**
_Note: If there are visual changes to the component, make an issue associated with that component, add details about the changes in the issue, and link to it from here._

- [x] #7582
- [x] #7192
- [x] #7584
- [x] #7047
- [x] #7197
- [x] Select: #7048 
- [x] TextField: #7048
- [x] Filter: #7048 
- [x] #7199
- [x] #7205
- [x] #7206
- [x] #7598
- [x] #7198
- [x] #7583
- [x] Video thumbnail - #7046
- [x] Top bar
- [x] Resource list
- [x] Range slider
- [x] Popover
- [x] Page actions
- [x] Pagination
- [x] Modal
- [x] Link
- [x] Index table
- [x] Footer help
- [x] Exception list
- [x] Contextual save bar
- [x] Data table
- [x] Date picker
- [x] Color picker
- [x] Account connection
- [x] Badge
- [x] Banner
- [x] Button
- [x] Button group
- [x] Callout card
- [x] Checkbox
- [x] Choice list
- [x] Grid (n/a)
- [x] Inline error
- [x] Media card
- [x] Progress bar (n/a)
- [x] Radio button
- [x] Setting toggle
- [x] Spinner (n/a)
- [x] Skeleton body text (n/a)
- [x] Skeleton display text (n/a)
- [x] Skeleton thumbnail (n/a)
- [x] Tabs
- [x] Tag
- [x] Thumbnail (n/a)
- [x] Tooltip

https://github.com/Shopify/polaris/issues/6794#tasklist-block-d1b06d8b-1491-4006-b3b0-ac1270fa5ca3

**Comment by sarahill** [comment]
@nayeob-kim just throwing in a couple things from our chat to look out for during the migration work:

- should we update `headingXs` to use a semibold weight instead of bold?
- are we finding we're using `bodyMd–medium` in a lot of different places? keep track of where

**Comment by nayeobkim** [comment]
@sarahill On the second point, you mean bodyMd-Medium, right?

**Comment by sarahill** [comment]
Ah yep. Updated my comment 👍
