### ISSUE TITLE
Connect GitHub discussions

### ISSUE THREAD

**Issue by SeanyB** [Shopify/polaris-react-archive#7940]
### Tasks

Design
- [x] Create Github discussions
- [x] Create a simple discussion template and update all threads (Selene)

Eng
- [x] Add links to respective page on the doc site (Johan)
- [x] Add new pattern index link to (Johan)

### GitHub discussion links
| Added | Topic | Link |
|--------|--------|--------|
| ✅ | Polaris Patterns general | `https://github.com/Shopify/polaris/discussions/categories/pattern-documentation` | 
| ✅ | Date picking | `https://github.com/Shopify/polaris/discussions/7853` |
| ✅ | Resource index layout | `https://github.com/Shopify/polaris/discussions/8215` |
| ✅ | Resource details layout | `https://github.com/Shopify/polaris/discussions/8216` |
| ✅ | App settings layout | `https://github.com/Shopify/polaris/discussions/8217` |

**Comment by johanstromqvist** [comment]
All urls are updated. Closing.
