### ISSUE TITLE
[Layout training] Create Layout resource page 

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#8561]
Create a Layout training resource page under the `Design` category on polaris.shopify.com

[Google doc](https://docs.google.com/document/d/1MdHxd-KvmrIxIYKw8ZM_f6sGdKD8j-9r314CHajDAAk/edit#) for content writing

In sequence order:

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/8633
- [ ] https://github.com/Shopify/polaris/issues/8562
- [ ] https://github.com/Shopify/polaris/issues/8637
- [ ] https://github.com/Shopify/polaris/issues/8632
- [ ] https://github.com/Shopify/polaris/issues/8563
- [ ] https://github.com/Shopify/polaris/issues/8564
- [ ] https://github.com/Shopify/polaris/issues/8635
- [ ] https://github.com/Shopify/polaris/issues/8634
```
