### ISSUE TITLE
[Layout foundations] Align Page with SkeletonPage

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#8575]
SkeletonPage was rebuilt with layout primitives and adjusted to make sure it matches the Page component for spacing and alignment. This means that mixins that were previously shared between the two components are now missing and the two components can get our of sync with eachother

```[tasklist]
### Tasks
- [ ] Rebuild Page with layout primitives
- [ ] Remove all shared mixins
- [ ] Render Page component from SkeletonPage (no duplication of markup)
```
