### ISSUE TITLE
Add Monorail search events to docs

### ISSUE THREAD

**Issue by yurm04** [Shopify/polaris-react-archive#8696]
Mirror the .dev site search even tracking so that we have data for future .dev learnings

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/8703
- [ ] https://github.com/Shopify/polaris/issues/8704
- [ ] https://github.com/Shopify/polaris/issues/8705
```

**Comment by yurm04** [comment]
we're not able to use monorail for this project. closing all monorail related tickets
