### ISSUE TITLE
[Button and Link quality] [Milestone 1] `Link` guidance and documentation

### ISSUE THREAD

**Issue by sarahill** [Shopify/polaris-react-archive#8791]
## Best practices

- [ ] **Content design**
        UI language and information design considerations have been incorporated into component design.
- [ ] **Usage guidelines**
        Clear documentation on when to use the component and all considerations for usage within the Admin.

## Component details

- [ ] **Design tokens**
        All design attributes (color, typography, layout, motion, etc.) use Polaris design tokens.
- [ ] **Defined variants and props**
        Includes relevant variants (optional iconography, selection, error state, etc.)
- [ ] **Defined behaviors**
        Documented behaviors such as unique keyboard navigation, text/component wrapping, truncation or overflow of content.
- [ ] **Component spec**
        Anatomy of component and all its parts for builders to understand how something is composed and which elements are required vs optional.

## Accessibility

- [ ] **Accessible use of color**
        Color is not used as the only visual means of conveying information (WCAG 2.0 1.4.1).
- [ ] **Accessible contrast for text**
        Text has a contrast ratio of at least 4.5:1 for small text and at least 3:1 for large text (WCAG 2.0 1.4.3).
- [ ] **Accessible contrast for UI components**
        Visual information required to identify components and states (except inactive components) has a contrast ratio of at least 3:1 (WCAG 2.1 1.4.11).
- [ ] **Keyboard interactions**
        Follows WCAG 2.0 standards for keyboard accessibility guidelines and includes a description of the keyboard interactions
