### ISSUE TITLE
Add consistent descriptions for every page and component section. 

### ISSUE THREAD

**Issue by jjgali** [Shopify/polaris-react-archive#8809]
## Issue summary

Currently, some pages on the site have descriptions, and others don't. Referring to the Components specifically, right now `Layout and structure` is the only section with a description. 

## Proposal

Every page should have a description, and these descriptions should follow an established set of guidelines (Style, length, available actions, etc.). Based on those guidelines, we should write new descriptions and edit existing ones.

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/8810
- [ ] https://github.com/Shopify/polaris/issues/8811
- [ ] https://github.com/Shopify/polaris/issues/8812
```
