### ISSUE TITLE
Contribution enhancements

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#9008]
## Summary
Last year we rolled out new documentation on contributing to Polaris. We now want to fill in some of the holes we are seeing and experiences after that work. This is mostly focused on brining clarity around what should be contributed and what shouldn't. This will help builders have proper expectations and reduce rejected contributions at the PR stage by surfacing things further upstream.

## Issues we are seeing
We still lack documentation around how we decide if something is a good candidate for contribution. This leads to folks submitting PR's that don't align with Polaris vision. This wastes builder time and decreases morale of contributor. This is especially true of larger contributions where it would be much better if the Polaris team was involved much earlier in the design process. 
3. 

```[tasklist]
### Tasks
- [x] Review survey results
- [ ] Set up 5 interviews to learn about current concerns in contribution process
- [ ] Document summary of findings
- [ ] Put interview summary in centralized location for future reference
- [x] Document thinking about "when/if" something should be contributed (substantial contributions/flow chart)
- [x] v1 of RFC process
- [x] Create interview tracker/research repo so we don't talk to same folks constantly
- [ ] https://github.com/Shopify/polaris/issues/9034
- [ ] https://github.com/Shopify/polaris/issues/9037
- [ ] https://github.com/Shopify/polaris/issues/9127
```
