### ISSUE TITLE
Document repository 

### ISSUE THREAD

**Issue by heyjoethomas** [Shopify/polaris-react-archive#9009]
## Issue summary
There is currently no central repository for internal Polaris documents. This makes it hard to know what has and hasn't been documented. This leads to misalignment within the team, lack of visibility and expectations. 

## Desired state
Everyone within the Polaris team should have access to key documents that share our core processes as well as key documents like research findings.

```[tasklist]
### Tasks
- [ ] Create a central repo in Vault team page
- [ ] Either link or add known documents to document repo
- [ ] Ask for folks to review and edit stale docs so everything is relevant. 
```
