### ISSUE TITLE
Top bar improvements to match production

### ISSUE THREAD

**Issue by gladys-ng** [Shopify/polaris-react-archive#9023]
### Problem

The top bar component doesn't match what's in production. [Link to branch](https://www.figma.com/file/4dAAt5iFPSaxUKiYVKrkYj/branch/ZwzWB7vrD2EBtfJVHfXpvS/Polaris-Components?node-id=434%3A2197&t=a7Dio9JBa90BerVr-1)
```[tasklist]
### Tasks
- [x] Add border to search field
- [x] Add hover states to search field
- [x] Add assets persistent setup guide
- [x] Add assets for alerts button
- [x] Change variant `📱568 px` to `📱490 px` to better match the small breakpoint `--p-breakpoints-sm`
- [x] Change variant `min-width` (1030 px) to  1040 px to better match the large breakpoint `--p-breakpoints-lg`
```
