### ISSUE TITLE
[Epic] Remove conditional se23 logic from polaris-react components

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#9913]
1. Branch off of `next`
2. Remove any `polarisSummerEditions2023` flag in `tsx` files. Keep the code with the boolean set to `true`), remove the hook and hook import.
3. Make styles inside `se23 &` blocks in the `scss` files the mainline styles, delete any styles that were being overridden or are unused. Be careful about specificity and regressions.
4. Make sure to do steps 2-3 for any subcomponents, you can search within the component folder to make sure all `se23` and `polarisSummerEditions2023` are removed (be wary of flag renames/aliases)
5. Tophat on storybook that the styles look like the new language with the flag both on and off. You can also compare with the [production storybook ](https://storybook.polaris.shopify.com/?path=/story/playground--details-page&globals=polarisSummerEditions2023:true), set the breakpoint size, then compare the two tabs
> Edit: with the flag turned off there may be some token related difference or imported polaris components that haven't been fixed yet. You can ignore those for now as they should be covered by different projects/issues
6. In tests, remove any `polarisSummerEditions2023 false` describe blocks and delete any  `polarisSummerEditions2023: true` in the app mounts (more info [here](https://github.com/Shopify/polaris/pull/9860))
~~7. Add the component you've cleaned up to the changelog list (https://github.com/Shopify/polaris/blob/next/.changeset/tall-chicken-repeat.md)~~ 
7. Create a PR pointing to the [next](https://github.com/Shopify/polaris/tree/next) branch```[tasklist]
8. Skip Changelog on the PR (see https://github.com/Shopify/polaris/issues/10035 for more info why)

```[tasklist]
### Tasks
- [x] https://github.com/Shopify/polaris/pull/9906
- [x] https://github.com/Shopify/polaris/issues/9910
- [ ] https://github.com/Shopify/polaris/issues/9909
- [ ] https://github.com/Shopify/polaris/issues/9916
- [ ] https://github.com/Shopify/polaris/issues/9917
- [ ] https://github.com/Shopify/polaris/issues/9918
- [ ] https://github.com/Shopify/polaris/issues/9919
- [ ] https://github.com/Shopify/polaris/issues/9920
- [ ] https://github.com/Shopify/polaris/issues/9921
- [ ] https://github.com/Shopify/polaris/issues/9922
- [ ] https://github.com/Shopify/polaris/issues/9923
- [ ] https://github.com/Shopify/polaris/issues/9924
- [ ] https://github.com/Shopify/polaris/issues/9925
- [ ] https://github.com/Shopify/polaris/issues/9926
- [ ] https://github.com/Shopify/polaris/issues/9927
- [ ] https://github.com/Shopify/polaris/issues/9928
- [ ] https://github.com/Shopify/polaris/issues/9929
- [ ] https://github.com/Shopify/polaris/issues/9930
- [ ] https://github.com/Shopify/polaris/issues/9931
- [ ] https://github.com/Shopify/polaris/issues/9932
- [ ] https://github.com/Shopify/polaris/issues/9933
- [ ] https://github.com/Shopify/polaris/issues/9934
- [ ] https://github.com/Shopify/polaris/issues/9935
- [ ] https://github.com/Shopify/polaris/issues/9936
- [ ] https://github.com/Shopify/polaris/issues/9937
- [ ] https://github.com/Shopify/polaris/issues/9938
- [ ] https://github.com/Shopify/polaris/issues/9939
- [ ] https://github.com/Shopify/polaris/issues/9940
- [ ] https://github.com/Shopify/polaris/issues/9941
- [ ] https://github.com/Shopify/polaris/issues/9942
- [ ] https://github.com/Shopify/polaris/issues/9943
- [ ] https://github.com/Shopify/polaris/issues/9944
- [ ] https://github.com/Shopify/polaris/issues/9945
- [ ] https://github.com/Shopify/polaris/issues/9946
- [ ] https://github.com/Shopify/polaris/issues/9947
- [ ] https://github.com/Shopify/polaris/issues/9948
- [ ] https://github.com/Shopify/polaris/issues/9949
- [ ] https://github.com/Shopify/polaris/issues/9950
- [ ] https://github.com/Shopify/polaris/issues/9951
- [ ] https://github.com/Shopify/polaris/issues/9952
- [ ] https://github.com/Shopify/polaris/issues/9953
- [ ] https://github.com/Shopify/polaris/issues/9954
- [ ] https://github.com/Shopify/polaris/issues/9955
- [ ] https://github.com/Shopify/polaris/issues/9957
- [ ] https://github.com/Shopify/polaris/issues/9958
- [ ] https://github.com/Shopify/polaris/issues/9959
- [ ] https://github.com/Shopify/polaris/issues/9960
- [ ] https://github.com/Shopify/polaris/issues/9961
- [ ] https://github.com/Shopify/polaris/issues/9962
- [ ] https://github.com/Shopify/polaris/issues/9963
- [ ] https://github.com/Shopify/polaris/issues/9964
- [ ] https://github.com/Shopify/polaris/issues/9965
- [ ] https://github.com/Shopify/polaris/issues/9966
- [ ] https://github.com/Shopify/polaris/issues/9967
- [ ] https://github.com/Shopify/polaris/issues/9968
- [ ] https://github.com/Shopify/polaris/issues/9969
- [ ] https://github.com/Shopify/polaris/issues/9970
- [ ] https://github.com/Shopify/polaris/issues/9971
- [ ] https://github.com/Shopify/polaris/issues/9972
- [ ] https://github.com/Shopify/polaris/issues/9973
- [ ] https://github.com/Shopify/polaris/issues/9974
- [ ] https://github.com/Shopify/polaris/issues/9975
- [ ] https://github.com/Shopify/polaris/issues/9976
```
