### ISSUE TITLE
[Epic] API alignment

### ISSUE THREAD

**Issue by kyledurand** [Shopify/polaris-react-archive#9914]
```[tasklist]
### General changes
- [ ] https://github.com/Shopify/polaris/issues/10165
- [ ] https://github.com/Shopify/polaris/issues/10298
- [ ] https://github.com/Shopify/polaris/issues/9978
- [ ] https://github.com/Shopify/polaris/issues/10161
- [ ] https://github.com/Shopify/polaris/issues/9980
- [ ] https://github.com/Shopify/polaris/issues/10272
- [ ] https://github.com/Shopify/polaris/issues/9979
- [ ] https://github.com/Shopify/polaris/issues/10099
- [ ] https://github.com/Shopify/polaris/issues/10233
- [ ] https://github.com/Shopify/polaris/issues/10084
- [ ] https://github.com/Shopify/polaris/issues/10085
- [ ] https://github.com/Shopify/polaris/issues/10095
- [ ] https://github.com/Shopify/polaris/issues/10260
```

```[tasklist]
### Component changes
- [ ] https://github.com/Shopify/polaris/issues/10484
- [ ] https://github.com/Shopify/polaris/issues/9977
- [ ] https://github.com/Shopify/polaris/issues/10277
- [ ] https://github.com/Shopify/polaris/issues/10247
- [ ] https://github.com/Shopify/polaris/issues/10269
- [ ] https://github.com/Shopify/polaris/issues/10002
- [ ] https://github.com/Shopify/polaris/issues/9994
- [ ] https://github.com/Shopify/polaris/issues/10259
- [ ] https://github.com/Shopify/polaris/issues/10267
- [ ] https://github.com/Shopify/polaris/issues/9981
- [ ] https://github.com/Shopify/polaris/issues/10050
- [ ] https://github.com/Shopify/polaris/issues/10208
- [ ] https://github.com/Shopify/polaris/issues/10126
- [ ] https://github.com/Shopify/polaris/issues/10047
- [ ] https://github.com/Shopify/polaris/issues/10033
- [ ] https://github.com/Shopify/polaris/issues/10049
- [ ] https://github.com/Shopify/polaris/issues/10064
- [ ] https://github.com/Shopify/polaris/issues/9982
- [ ] https://github.com/Shopify/polaris/issues/10197
- [ ] https://github.com/Shopify/polaris/issues/10202
- [ ] https://github.com/Shopify/polaris/issues/10770
```

```[tasklist]
### Component name changes
- [ ] https://github.com/Shopify/polaris/issues/9983
- [ ] https://github.com/Shopify/polaris/issues/9984
- [ ] https://github.com/Shopify/polaris/issues/9985
- [ ] https://github.com/Shopify/polaris/issues/10107
```
```[tasklist]
### Delete deprecated components
- [ ] https://github.com/Shopify/polaris/issues/9996
```
