### ISSUE TITLE
[Epic] Globally remove all conditional se23 logic from polaris-react

### ISSUE THREAD

**Issue by sophschneider** [Shopify/polaris-react-archive#9915]
after https://github.com/Shopify/polaris/issues/9913 is completed we need to

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/polaris/issues/10189
- [ ] https://github.com/Shopify/polaris/issues/10191
- [ ] https://github.com/Shopify/polaris/issues/10190
- [ ] https://github.com/Shopify/polaris/issues/10192
- [ ] https://github.com/Shopify/polaris/issues/10193
- [ ] https://github.com/Shopify/polaris/issues/10194
- [ ] https://github.com/Shopify/polaris/pull/10239
- [ ] https://github.com/Shopify/polaris/pull/10241
- [ ] https://github.com/Shopify/polaris/pull/10243
- [ ] https://github.com/Shopify/polaris/pull/10242
- [ ] https://github.com/Shopify/polaris/pull/10244
- [ ] https://github.com/Shopify/polaris/issues/10254
- [x] Do a final code search for `se23`, `polarisSummerEditions2023`, `polarisSummerEditions2023ShadowBevelOptOut` etc. to make sure all conditional code is removed
```

### Note
We can remove `$se23ShadowBevelOptOut` but not `$se23` since a lot of our consuming repos still use the classname and we don't want to affect their styles.

Sources:
* se23 class name used in many consuming repos internally: https://grokt.shopify.io/results?q=Polaris-Summer-Editions-2023
* shadow bevel class name only in polaris: https://grokt.shopify.io/results?q=Polaris-SE23-Shadow-Bevel-Opt-Out

**Comment by sophschneider** [comment]
We can resume this work once https://github.com/Shopify/polaris/pull/10423 ships :D
