### ISSUE TITLE
[Epic] Polaris tokens reconciliation

### ISSUE THREAD

**Issue by aaronccasanova** [Shopify/polaris-react-archive#9986]
```[tasklist]
### Token reconciliation
- [x] Identify and document experimental design tokens created during the Uplift
- [x] Compare and analyze current and experimental Polaris tokens
- [x] Analyze existing token groups to determine where to introduce semantics
- [x] Determine what token groups are in scope for reconciliation
- [x] Consolidate current and experimental tokens to a finalized set
```

```[tasklist]
### Theming
- [ ] https://github.com/Shopify/polaris/issues/9987
- [ ] https://github.com/Shopify/polaris/issues/9988
- [ ] https://github.com/Shopify/polaris/issues/9989
- [ ] https://github.com/Shopify/polaris/issues/10043
- [x] Deprecate non theme related exports in v12 (metadata, tokens, individual token groups, etc)
- [ ] Deprecate v0 polaris.shopify.com tokens REST API (to avoid enabling multi-theme support)
- [ ] Update documentation to reflect the changes made to support theming
- [x] Remove * exports from Polaris tokens (e.g. use explicit named exports)
```

```[tasklist]
### Rollout and migrations
- [x] Identify migration paths that can leverage the Polaris migrator
- [x] Determine what migration paths need to be handled manually
- [ ] https://github.com/Shopify/polaris/issues/10301
- [ ] https://github.com/Shopify/polaris/issues/10302
- [x] After migrations add deprecated custom properties to stylelint-polaris
```

```[tasklist]
### Stretch goals
- [ ] Establish a pattern for theme/token overrides
- [ ] Explore responsive tokens
- [x] [Polaris tokens] Rename `createVar` to `createVarName`
- [ ] Investigate Chromatic Story Modes: https://www.chromatic.com/docs/modes
```
